spring:
  data:
    mongodb:
      uri: mongodb://localhost/
      port: 27017
      username: admin
      password: admin
      database: database

scheduler:
  calculation:
    delay: 0 0 9 * * ? # Run at 9 AM
